// Code generated by hertz generator.

package main

import (
	_ "github.com/ACaiCat/memo/docs"
	"github.com/ACaiCat/memo/internal"
	"github.com/ACaiCat/memo/internal/dal"
	"github.com/ACaiCat/memo/pkg/config"
	"github.com/hertz-contrib/swagger"
	swaggerFiles "github.com/swaggo/files"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/hertz-contrib/logger/accesslog"
)

// @title Memo
// @version 1.0
// @description A demo of memo api

// @contact.name ACaiCat
// @contact.url https://github.com/ACaiCat

// @license.name The MIT License (MIT)
// @license.url https://mit-license.org/

// @host localhost:8888
// @BasePath /
// @schemes http

// @securityDefinitions.apikey	ApiKeyAuth
// @in							header
// @name						Authorization
// @description				Description for what is this security definition being used
func main() {
	h := server.Default(server.WithHostPorts(config.GetConfig().ServerConfig.Listen))

	if config.GetConfig().ServerConfig.Debug {
		hlog.SetLevel(hlog.LevelDebug)
		url := swagger.URL("http://localhost:8888/swagger/doc.json")
		h.GET("/swagger/*any", swagger.WrapHandler(swaggerFiles.Handler, url))
	}

	dal.InitDal()
	h.Use(accesslog.New())

	router.SetupRouter(h, dal.DB, dal.Cache)
	h.Spin()
}
